# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Mod Properties
mod_version = 1.4.0-mc1.21.1
maven_group = dev.bvengo
archives_base_name = soundcontroller

# Versioning
minecraft_version=1.21.1

## Fabric: https://fabricmc.net/develop
## ModMenu: https://maven.terraformersmc.com/modmenu
loader_version=0.18.4
loom_version=1.17-SNAPSHOT
fabric_version=0.116.9+1.21.1
modmenu_version=11.0.3

## NeoForged https://neoforged.net
## ModDev https://plugins.gradle.org/plugin/net.neoforged.moddev
## Annotations https://mvnrepository.com/artifact/org.jetbrains/annotations
neoforge_version=21.1.211
neoforge_moddev_version=2.0.141
jetbrains_annotations_version=26.1.0
